#!/bin/bash

set -e

# Install OSS-CAD-Suite
wget -q https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2021-09-23/oss-cad-suite-linux-x64-20210923.tgz
tar -xf oss-cad-suite-linux-x64-20210923.tgz


SCALA_VERSION=2.12.10 ALMOND_VERSION=0.9.1

# Install coursier
curl -Lo coursier https://git.io/coursier-cli
chmod +x coursier

# Install almond
./coursier bootstrap \
    -r jitpack \
    -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
    sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
    --sources --default=true \
    -o almond
./almond --install
